// Generated by https://quicktype.io

export interface VideoContent {
  adult:             boolean;
  backdrop_path:     string;
  genre_ids:         number[];
  id:                number;
  original_language: string;
  original_title:    string;
  overview:          string;
  popularity:        number;
  poster_path:       string;
  release_date:      string;
  title:             string;
  name:             string;
  video:             boolean;
  vote_average:      number;
  vote_count:        number;
}

// Generated by https://quicktype.io

export interface VideoLinks {
  id:      number;
  results: Result[];
}

export interface Result {
  iso_639_1:    ISO639_1;
  iso_3166_1:   ISO3166_1;
  name:         string;
  key:          string;
  site:         Site;
  size:         number;
  type:         string;
  official:     boolean;
  published_at: string;
  id:           string;
}

export enum ISO3166_1 {
  Us = "US",
}

export enum ISO639_1 {
  En = "en",
}

export enum Site {
  YouTube = "YouTube",
}
